### PR TITLE
Fix starttime issue

### PR DESCRIPTION
**Pull request by jugaltheshah**

### CODE REVIEW

**Comment by cilindrox** [comment]
could you check this one @igorgolovanov ?

**Comment by jugaltheshah** [comment]
> could you check this one @igorgolovanov ?

Sorry I should have closed this one. It was a workaround for a strange error we were getting during a release, but I don't think it should be necessary. The circumstances were, we were getting an error on [this line](https://github.com/pagerinc/metrics-client/pull/49/files#diff-6d186b954a58d5bb740f73d84fe39073L115), but there doesn't seem to be a reason it would do that. If anything @igorgolovanov, could you see why that might be?

**Comment by cilindrox** [comment]
just ran into this myself when booting a new instance using this from scratch:

```json
{
"data":"Cannot read property 'startTime' of undefined","stack":"TypeError: Cannot read property 'startTime' of undefined\n    at Object.server.events.on [as listener] (/home/node/app/node_modules/@pager/metrics-client/lib/index.js:115:64)\n    at module.exports.internals.Podium.internals.Podium.emit (/home/node/app/node_modules/@hapi/podium/lib/index.js:224:107)\n    at Request._finalize (/home/node/app/node_modules/@hapi/hapi/lib/request.js:447:27)\n    at Request._reply (/home/node/app/node_modules/@hapi/hapi/lib/request.js:391:14)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","type":"Error","v":1}
```

**Comment by cilindrox** [comment]
created #51 - @igorgolovanov would appreciate your help with this one.

**Comment by igorgolovanov** [comment]
it's not good to fill startTime in response event when request-lifecycle already finished. This will cause the problem with invalid metrics (invalid request time) - we will see the good response times but it will invalid times.
We need to track only valid metrics or not track them at all -> https://github.com/pagerinc/metrics-client/pull/53

Closed.

**Pull request closed without merging**
