### PR TITLE
fix js-yaml vuln

### PR DESCRIPTION
**Pull request by cilindrox**
ref: nodeca/js-yaml#480

### CODE REVIEW

**Comment by cilindrox** [comment]
@igorgolovanov there must be some funky linking going on, wondering how was circle able to run the tests without those changes?

**Comment by igorgolovanov** [comment]
Need to change `test` script

> @igorgolovanov there must be some funky linking going on, wondering how was circle able to run the tests without those changes?

I'm shocked. Seems it restored node_modules from cache...

**Comment by cilindrox** [comment]
alright, the tests errored - but the exit code is still `0` - something funny's going on with lab/code

**Comment by cilindrox** [comment]
@igorgolovanov added step to drop cache on dep changes, updated code with namespaced refs - tests running as expected now.

**Pull request merged**
